### ISSUE TITLE
Features To-Do

### ISSUE THREAD

**Issue by simonwalsh** [DynamoMTL/dynamo-ops#10]
(Will keep adding stuff here)

- [x] Code highlighting
- [x] Category page intro support
- [x] remove robots.txt
- [x] Article length/time indicator 
- [x] Meta stuff (Title, etc.)
- [x] Search ?
- [x] get some of that Medium love in the article styling
- [x] ESLint
- [x] Have a loader / page transition
- [x] Hook up the CI : maybe http://luke.vivier.ca/wintersmith-with-wercker/
- [x] custom domain : https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/
- [x] homepage have long section if more than X articles (try)

Design QA
- [x] pattern in the header
- [ ] smaller fonts for articles/tags
- [x] hover on links
- [x] underline clearing descenders for links
- [ ] add footer
- [ ] body elastic scroll color
- [ ] reading bar
- [ ] CTAs in the header
- [ ] article arrow back to cat
- [ ] article title (3 min read)
- [x] narrow category listing
- [x] cat hero push liknks right
- [x] image bleed like quotes
- [x] narrow article 12 rem
- [x] quote and title blue
- [ ] responsify

**Comment by simonwalsh** [comment]
- [ ] prose date
- [ ] images upload
